name: java

on:
  push:
    paths:
    - java/**
  pull_request:
    paths:
    - java/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: SetupJDK17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Permissions
      run: chmod +x mvnw
      working-directory: ./java
    - name: BuildMaven
      run: ./mvnw -B package
      working-directory: ./java
